application:
  name: simplewebapp

deployment:
  replicas: 2
  
image:
  repo: csudharsan-docker.jfrog.io
  name: simplewebapp
  tag: latest
  containerport: 80
  secret: regcred

service:
  type: NodePort
  port: 80
  targetport: 80
  nodeport: 30007