apiVersion: v1
kind: ReplicationController
metadata:
  name: simplewebapp
spec:
  replicas: 3
  selector:
    app: simplewebapp
  template:
    metadata:
      name: simplewebapp
      labels:
        app: simplewebapp
    spec:
      containers:
      - name: simplewebapp
        image: nginx
        ports:
        - containerPort: 80
