apiVersion: v1
kind: Service
metadata:
  name: simplewebapp-svc
spec:
  selector:
    app: simplewebapp
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
   # nodePort: 30036
    protocol: TCP