---
- hosts: kubernetes-master
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    shell: kubeadm init 
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest=/home/jenkins/{{ token_file }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
  - name: get the k8 version for weave-net
    shell: echo 'kubectl version | base64 | tr -d '\n'
    register: kversion
  - name: Install Network Add-on Weave-Net
    command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{kversion}}"
