---
- hosts: kubernetes-master
  become: yes
  vars_files:
  - app_env_variables
  tasks:
  - name: Copy ReplicationController.yml 
    copy:
      src: /home/jenkins/workspace/VzInfyPOC-SimpleWebAppBuild/kubernetes_yaml
      dest: /home/jenkins/

  - name: Create ReplicationController
    shell: sudo kubectl create -f /home/jenkins/kubernetes_yaml/deployment.yml
    
  - name: Create Service
    shell: sudo kubectl create -f /home/jenkins/kubernetes_yaml/service.yml
