---
- hosts: kubernetes-master
  vars_files:
  - app_env_variables
  tasks:
  - name: Copy ReplicationController.yml 
    copy:
      src: /home/jenkins/workspace/VzInfyPOC-SimpleWebAppBuild/kubernetes_yaml
      dest: /home/jenkins/

  - name: Create ReplicationController
    shell: kubectl create -f /home/jenkins/kubernetes_yaml/rc.yml

  - name: Create Service
    shell: kubectl create -f /home/jenkins/kubernetes_yaml/service.yml
