---
- hosts: kubernetes-master
  vars_files:
  - app_env_variables
  tasks:
  - name: Copy ReplicationController.yml 
    copy:
      src: /home/jenkins/workspace/VzInfyPOC-SimpleWebAppBuild/kubernetes_yaml
      dest: /home/jenkins/kubernetes_yaml
  
  - name: Create secret 
    shell: kubectl create secret docker-registry regcred --docker-server={{jfrogrepo}} --docker-username={{jfroguser}} --docker-password={{jfrogpass}} --docker-email={{jfrogemail}}
  
  - name: Create ReplicationController
    shell: kubectl create -f rc.yml
      args:
        chdir: /home/jenkins/kubernetes_yaml/

  - name: Create Service
    shell: kubectl create -f service.yml
      args:
        chdir: /home/jenkins/kubernetes_yaml/