apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apache-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-apache-container1
        image: 2681/webapp
       
