apiVersion: v1
kind: Service
metadata:
  name: my-apache-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
   # nodePort: 30036
    protocol: TCP
