---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /home/jenkins/workspace/VzInfyPOC-SimpleWebAppBuild/scripts/install_kubeadm.sh
      dest: /home/jenkins/install_kubeadm.sh

  - name: Executing the script to install kubeadm
    shell: bash /home/jenkins/install_kubeadm.sh

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
