---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /home/jenkins/workspace/VzInfyPOC-SimpleWebAppBuild/scripts/install_kubeadm.sh
      dest: /home/jenkins/install_kubeadm.sh

  - name: Executing the script to install kubeadm
    shell: bash /home/jenkins/install_kubeadm.sh

  - name: Installing required packages
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
